version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.1
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: filp/whoops
    versions:
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.18
    - 4.4.19
    - 4.4.20
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: resolve-url-loader
    versions:
    - ">= 3.a, < 4"
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
