language: php
php: 7.1.8
sudo: required

branches:
  only:
    - master
    - develop

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files

services:
  - postgresql

before_script:
  - cp .env.travis .env

  - composer self-update
  - composer install --no-interaction

  - php artisan key:generate
  - psql -c 'create database travis_ci_test;' -U postgres

  - yarn install
  - yarn dev

script:
  - php artisan migrate:fresh --seed
  - composer test
  - yarn test
