language: php
php: "7.1"
sudo: required

branches:
  only:
    - master
    - develop

cache:
  # yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

  - cp .env.travis .env
  - composer install --no-interaction --no-suggest
  - php artisan key:generate
  - php artisan migrate:fresh --seeder=BaseTableSeeder

  - yarn install
  - yarn prod

script:
  - composer test
  - yarn test
  - vendor/bin/phpunit
